# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

# 监听
on:
  push:
  	# 向master push的时候执行
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  	# 默认情况最新的ubuntu的系统
    runs-on: ubuntu-latest
    steps:
    #执行use后执行什么，把源码提取出去
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
      # 参数设置java的版本
        java-version: 11
    - name: Build with Maven
      # 在target中生成jar包，完成测试 构件 打包
      run: mvn -B package --file pom.xml
